import { Preset } from '../models/preset';

export const PRESETS: Preset[] = [
  {
    name: 'kaspa preset',
    selectedInstrument: 'piano',
    bloomStrength: 0,
    bloomRadius: 1.1,
    bloomThreshold: 0.18,
    soundTrackIndex: null,
    soundDirection: 1,
    unsetBlockColor: '#dddddd',
    blueBlockColor: '#70c7ba',
    redBlockColor: '#d64045',
    selectedColor: '#00ff00',
    mergeSetColor: '#ffff00',
    lineColor: '#777777',
    lineColorSelectedParent: '#ffd500',
    selectedChainColor: '#ffff00',
  },
  {
    name: 'sunset preset',
    selectedInstrument: 'piano',
    bloomStrength: 4,
    bloomRadius: 1.1,
    bloomThreshold: 0.18,
    soundTrackIndex: 3,
    soundDirection: 1,
    unsetBlockColor: '#dddddd',
    blueBlockColor: '#ffd500',
    redBlockColor: '#d64045',
    selectedColor: '#00ff00',
    mergeSetColor: '#00ffcc',
    lineColor: '#812fa7',
    lineColorSelectedParent: '#fbff00',
    selectedChainColor: '#ff7575',
  },
  {
    name: 'matrix preset',
    selectedInstrument: 'piano',
    bloomStrength: 3.6,
    bloomRadius: 1.2,
    bloomThreshold: 0.18,
    soundTrackIndex: 1,
    soundDirection: -1,
    unsetBlockColor: '#ffffff',
    blueBlockColor: '#00ff00',
    redBlockColor: '#d64045',
    selectedColor: '#00ff00',
    mergeSetColor: '#00b3ff',
    lineColor: '#545454',
    lineColorSelectedParent: '#00ffbf',
    selectedChainColor: '#e1ff00',
  },
  {
    name: 'stream preset',
    selectedInstrument: 'piano',
    bloomStrength: 3.6,
    bloomRadius: 1.2,
    bloomThreshold: 0.18,
    soundTrackIndex: 2,
    soundDirection: -1,
    unsetBlockColor: '#ffffff',
    blueBlockColor: '#3c9496',
    redBlockColor: '#ff0000',
    selectedColor: '#00ff00',
    mergeSetColor: '#00b3ff',
    lineColor: '#242442',
    lineColorSelectedParent: '#00ffbf',
    selectedChainColor: '#e1ff00',
  },
];
